import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import {getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendEmailVerification,reload,signOut,sendPasswordResetEmail} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {getFirestore,doc,getDoc,setDoc,collection,addDoc,getDocs,query,orderBy,serverTimestamp,updateDoc} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
import {firebaseConfig,institutionalDomains} from './config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id),show=(id,on)=>$(id).classList.toggle('hidden',!on);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const allowed=email=>institutionalDomains.some(d=>d.toLowerCase()===String(email).split('@')[1]?.toLowerCase());
let user,profile,attemptId,answers={},Q=[],sections=[],section=0,openedAt=Date.now(),textTimers={};
const status=msg=>$('authStatus').textContent=msg;
function authError(e){return ({'auth/email-already-in-use':'El correo ya tiene una cuenta. Ingresá o recuperá la contraseña.','auth/invalid-credential':'Credenciales incorrectas.','auth/weak-password':'La contraseña es demasiado débil.','auth/too-many-requests':'Demasiados intentos. Probá más tarde.'})[e.code]||e.message;}
$('authForm').onsubmit=async e=>{e.preventDefault();try{if(!allowed($('email').value))throw Error('Usá el dominio institucional habilitado.');await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);status('');}catch(e){status(authError(e))}};
$('register').onclick=async()=>{try{if(!allowed($('email').value))throw Error('Usá el dominio institucional habilitado.');if($('password').value.length<8)throw Error('Ingresá una contraseña de al menos 8 caracteres.');let r=await createUserWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);await sendEmailVerification(r.user);status('Te enviamos un correo para verificar tu cuenta.')}catch(e){status(authError(e))}};
$('recover').onclick=async()=>{try{if(!allowed($('email').value))throw Error('Escribí tu correo institucional.');await sendPasswordResetEmail(auth,$('email').value.trim());status('Si la cuenta existe, recibirás instrucciones por correo.')}catch(e){status(authError(e))}};
$('resend').onclick=async()=>{try{await sendEmailVerification(auth.currentUser);alert('Correo enviado.')}catch(e){alert(authError(e))}};
$('checkVerified').onclick=async()=>{await reload(auth.currentUser);await route(auth.currentUser)};
$('verifyLogout').onclick=$('logout').onclick=()=>signOut(auth);
$('profileForm').onsubmit=async e=>{e.preventDefault();const p={firstName:$('firstName').value.trim(),lastName:$('lastName').value.trim(),commission:$('commission').value.trim(),email:user.email};if(!p.firstName||!p.lastName||!p.commission)return;await setDoc(doc(db,'profiles',user.uid),{...p,updatedAt:serverTimestamp()});profile=p;await start()};
$('newAttempt').onclick=async()=>{if(!confirm('¿Iniciar un nuevo intento? El anterior quedará conservado en el historial.'))return;await closeAttempt();await createAttempt();draw()};
async function route(u){user=u;['setup','verify','profile','student'].forEach(x=>show(x,false));if(!u){show('setup',true);return}if(!allowed(u.email)){await signOut(auth);status('Correo no autorizado.');return}if(!u.emailVerified){show('verify',true);return}const p=await getDoc(doc(db,'profiles',u.uid));if(!p.exists()){show('profile',true);return}profile=p.data();await start()}
onAuthStateChanged(auth,u=>route(u).catch(e=>{console.error(e);status('No se pudo iniciar: '+e.message);show('setup',true)}));
async function start(){show('student',true);$('studentInfo').textContent=`${profile.firstName} ${profile.lastName} · ${profile.commission}`;let isTeacher = false;

try {
  const adminDoc = await getDoc(doc(db, 'admins', user.uid));
  isTeacher = adminDoc.exists();
} catch (error) {
  if (error.code !== 'permission-denied') {
    console.error('Error al verificar permisos docentes:', error);
    throw error;
  }
}

show('adminLink', isTeacher);Q=await (await fetch('./questions.json')).json();sections=[...new Set(Q.map(q=>q.section))];const ref=query(collection(db,'users',user.uid,'attempts'),orderBy('startedAt','desc'));const snap=await getDocs(ref);const open=snap.docs.find(d=>d.data().status==='open');if(open){attemptId=open.id;answers={};let rows=await getDocs(collection(db,'users',user.uid,'attempts',attemptId,'answers'));rows.forEach(d=>answers[d.id]=d.data())}else await createAttempt();openedAt=Date.now();draw();}
async function createAttempt(){let a=await addDoc(collection(db,'users',user.uid,'attempts'),{startedAt:serverTimestamp(),status:'open',commission:profile.commission,questionCount:Q.length});attemptId=a.id;answers={};await event('attempt_started',{questionId:-1});}
async function closeAttempt(){if(attemptId){await updateDoc(doc(db,'users',user.uid,'attempts',attemptId),{status:'closed',closedAt:serverTimestamp()});await event('attempt_closed',{questionId:-1})}}
async function event(type,data={}){if(!user||!attemptId)return;try{await addDoc(collection(db,'users',user.uid,'attempts',attemptId,'events'),{type,...data,at:serverTimestamp()})}catch(e){console.warn('Evento no guardado',e)}}
async function saveAnswer(i,patch){const prior=answers[i]||{},next={...prior,...patch};answers[i]=next;drawStats();await setDoc(doc(db,'users',user.uid,'attempts',attemptId,'answers',String(i)),{questionId:i,section:Q[i].section,type:Q[i].type,...next,updatedAt:serverTimestamp()});}
function drawStats(){let done=Object.values(answers).filter(a=>a.choice!==undefined||a.review).length;$('stats').textContent=`Intento actual: ${done} de ${Q.length} consignas respondidas o revisadas`}
function draw(){drawStats();$('tabs').innerHTML=sections.map((s,i)=>`<button class="tab ${i===section?'active':''}" data-section="${i}">${esc(s)}</button>`).join('');$('tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{section=Number(b.dataset.section);event('section_opened',{section:sections[section],questionId:-1});draw()});let items=Q.map((q,i)=>({...q,id:i})).filter(q=>q.section===sections[section]);let html=`<h2>${esc(sections[section])}</h2>`;if(section===4)html+='<figure class="financial-image"><img src="assets/estados.png" alt="Estados contables de Nexo Digital S.A. 2025 y 2026"><figcaption>Importes en millones de pesos. Para RIT y RPN, utilizar promedios.</figcaption></figure>';if(section===5)html+='<figure class="financial-image"><img src="assets/comparacion.svg" alt="Comparación de indicadores de Empresa A y B"><figcaption>Compará los indicadores y fundamentá tus conclusiones.</figcaption></figure>';if(section===6)html+='<p class="note">Una empresa vende un producto a $30.000 por unidad, tiene un costo variable unitario de $18.000, costos fijos de $14.400.000 y ventas previstas de 1.500 unidades. Suponer comportamiento lineal en el rango relevante.</p>';for(let j=0;j<items.length;j++){const q=items[j],a=answers[q.id]||{};html+=`<article><p class="small">Pregunta ${j+1} de ${items.length}</p><h3>${esc(q.prompt)}</h3>`;if(q.type==='mc'||q.type==='tf'){let opts=q.type==='tf'?['Verdadero','Falso']:q.options;html+=opts.map((o,k)=>`<label class="option"><input type="radio" name="q${q.id}" data-id="${q.id}" data-choice="${k}" ${a.choice===k?'checked':''}>${esc(o)}</label>`).join('');if(a.choice!==undefined){let correct=q.type==='tf'?a.choice===(q.answer?0:1):a.choice===q.answer;html+=`<div class="feedback ${correct?'good':'bad'}"><strong>${correct?'Correcto':'Revisá tu respuesta'}.</strong> Respuesta: ${esc(q.type==='tf'?(q.answer?'Verdadero':'Falso'):q.options[q.answer])}.<p>${esc(q.explain)}</p></div>`}}else{html+=`<textarea data-text="${q.id}" placeholder="Escribí tu razonamiento, fórmula o resultado...">${esc(a.text||'')}</textarea><button data-review="${q.id}">Guardar y ver respuesta orientativa</button>`;if(a.review)html+=`<div class="feedback"><strong>Respuesta orientativa:</strong> ${esc(q.answer)}<p>${esc(q.explain)}</p><small>La respuesta abierta no se califica automáticamente.</small></div>`}html+='</article>'}$('content').innerHTML=html;
$('content').querySelectorAll('[data-choice]').forEach(el=>el.onchange=async()=>{let i=+el.dataset.id,k=+el.dataset.choice,old=answers[i];await saveAnswer(i,{choice:k,revision:(old?.revision||0)+(old?.choice===undefined?0:1)});await event(old?.choice===undefined?'answer_selected':'answer_changed',{questionId:i,choice:k,correct:Q[i].type==='tf'?k===(Q[i].answer?0:1):k===Q[i].answer,secondsOnPage:Math.round((Date.now()-openedAt)/1000)});draw()});
$('content').querySelectorAll('[data-text]').forEach(el=>{el.oninput=()=>{let i=+el.dataset.text;clearTimeout(textTimers[i]);textTimers[i]=setTimeout(async()=>{await saveAnswer(i,{text:el.value,revision:(answers[i]?.revision||0)+1});await event('text_saved',{questionId:i,length:el.value.length});},1200)}});
$('content').querySelectorAll('[data-review]').forEach(el=>el.onclick=async()=>{let i=+el.dataset.review;clearTimeout(textTimers[i]);let t=$('content').querySelector(`[data-text="${i}"]`).value;await saveAnswer(i,{text:t,review:true});await event('explanation_viewed',{questionId:i,secondsOnPage:Math.round((Date.now()-openedAt)/1000)});draw()});openedAt=Date.now();}
