import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {getFirestore,doc,getDoc,collection,getDocs} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
import {firebaseConfig} from './config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let records=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&quot;'}[c]));
$('logout').onclick=()=>signOut(auth).then(()=>location.href='index.html');$('refresh').onclick=load;$('commission').onchange=draw;$('search').oninput=draw;
onAuthStateChanged(auth,async u=>{if(!u||!u.emailVerified){location.href='index.html';return}try{if(!(await getDoc(doc(db,'admins',u.uid))).exists()){$('status').textContent='Tu cuenta no tiene permisos docentes.';return}await load()}catch(e){$('status').textContent='Error de permisos o conexión: '+e.message}});
async function load(){try{$('status').textContent='Cargando respuestas…';records=[];const q=await(await fetch('./questions.json')).json(),profiles=await getDocs(collection(db,'profiles'));for(const prof of profiles.docs){let p=prof.data(),attempts=await getDocs(collection(db,'users',prof.id,'attempts'));for(const a of attempts.docs){let answers=await getDocs(collection(db,'users',prof.id,'attempts',a.id,'answers'));let events=await getDocs(collection(db,'users',prof.id,'attempts',a.id,'events'));let ev=events.docs.map(d=>d.data());for(const ans of answers.docs){let x=ans.data(),question=q[x.questionId],related=ev.filter(e=>e.questionId===x.questionId),viewed=related.filter(e=>e.type==='explanation_viewed').length;let correct='No automática';if(question?.type==='tf')correct=x.choice===undefined?'Sin respuesta':x.choice===(question.answer?0:1)?'Correcta':'Incorrecta';if(question?.type==='mc')correct=x.choice===undefined?'Sin respuesta':x.choice===question.answer?'Correcta':'Incorrecta';records.push({name:`${p.lastName||''}, ${p.firstName||''}`,email:p.email,commission:p.commission,attempt:a.id,started:a.data().startedAt?.toDate()?.toLocaleString('es-AR')||'',question:x.questionId+1,prompt:question?.prompt||'',response:question?.type==='tf'?(x.choice===0?'Verdadero':'Falso'):question?.type==='mc'?question.options[x.choice]:(x.text||''),correct,revisions:x.revision||0,views:viewed,seconds:related.reduce((acc,e)=>acc+((e.type==='answer_selected'||e.type==='answer_changed'||e.type==='explanation_viewed')?(e.secondsOnPage||0):0),0)})}}}const cs=[...new Set(records.map(r=>r.commission).filter(Boolean))].sort();$('commission').innerHTML='<option value="">Todas</option>'+cs.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('status').textContent='Datos actualizados.';draw()}catch(e){$('status').textContent='Error: '+e.message;console.error(e)}}
function filtered(){const c=$('commission').value,s=$('search').value.toLowerCase();return records.filter(r=>(!c||r.commission===c)&&(!s||`${r.name} ${r.email}`.toLowerCase().includes(s)))}
function draw(){const a=filtered();$('summary').textContent=`${new Set(a.map(x=>x.email)).size} estudiantes · ${new Set(a.map(x=>x.email+'|'+x.attempt)).size} intentos · ${a.length} respuestas guardadas`;$('rows').innerHTML=a.map(r=>`<tr>${[r.name,r.email,r.commission,r.attempt,r.started,r.question,r.prompt,r.response,r.correct,r.revisions,r.views,r.seconds].map((x,i)=>`<td ${i===6||i===7?'class="long"':''}>${esc(x)}</td>`).join('')}</tr>`).join('')}
$('export').onclick=()=>{const cols=['name','email','commission','attempt','started','question','prompt','response','correct','revisions','views','seconds'],rows=[cols,...filtered().map(r=>cols.map(c=>String(r[c]??'')))];const csv='\ufeff'+rows.map(row=>row.map(s=>'"'+s.replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));let a=document.createElement('a');a.href=url;a.download='contabilidad_gerencial_respuestas.csv';a.click();URL.revokeObjectURL(url)};
