import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {getFirestore,doc,getDoc,collection,getDocs} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
import {firebaseConfig} from './config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let records=[],questions=[],attemptsData=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&quot;'}[c]));
$('logout').onclick=()=>signOut(auth).then(()=>location.href='index.html');$('refresh').onclick=load;$('commission').onchange=draw;$('search').oninput=draw;$('attemptMode').onchange=draw;
onAuthStateChanged(auth,async u=>{if(!u||!u.emailVerified){location.href='index.html';return}try{if(!(await getDoc(doc(db,'admins',u.uid))).exists()){$('status').textContent='Tu cuenta no tiene permisos docentes.';return}await load()}catch(e){$('status').textContent='Error de permisos o conexión: '+e.message}});
async function load(){try{$('status').textContent='Cargando respuestas…';records=[];attemptsData=[];const q=await(await fetch('./questions.json')).json();questions=q;const profiles=await getDocs(collection(db,'profiles'));for(const prof of profiles.docs){let p=prof.data(),attempts=await getDocs(collection(db,'users',prof.id,'attempts'));for(const a of attempts.docs){attemptsData.push({uid:prof.id,name:`${p.lastName||''}, ${p.firstName||''}`,email:p.email,commission:p.commission,id:a.id,startedMs:a.data().startedAt?.toMillis()||0,started:a.data().startedAt?.toDate()?.toLocaleString('es-AR')||'',status:a.data().status||''});let answers=await getDocs(collection(db,'users',prof.id,'attempts',a.id,'answers'));let events=await getDocs(collection(db,'users',prof.id,'attempts',a.id,'events'));let ev=events.docs.map(d=>d.data());for(const ans of answers.docs){let x=ans.data(),question=q[x.questionId],related=ev.filter(e=>e.questionId===x.questionId),viewed=related.filter(e=>e.type==='explanation_viewed').length;let correct='No automática';if(question?.type==='tf')correct=x.choice===undefined?'Sin respuesta':x.choice===(question.answer?0:1)?'Correcta':'Incorrecta';if(question?.type==='mc')correct=x.choice===undefined?'Sin respuesta':x.choice===question.answer?'Correcta':'Incorrecta';records.push({name:`${p.lastName||''}, ${p.firstName||''}`,email:p.email,commission:p.commission,attempt:a.id,started:a.data().startedAt?.toDate()?.toLocaleString('es-AR')||'',question:x.questionId+1,section:question?.section||x.section||'Sin bloque',prompt:question?.prompt||'',response:question?.type==='tf'?(x.choice===0?'Verdadero':'Falso'):question?.type==='mc'?question.options[x.choice]:(x.text||''),correct,revisions:x.revision||0,views:viewed,seconds:related.reduce((acc,e)=>acc+((e.type==='answer_selected'||e.type==='answer_changed'||e.type==='explanation_viewed')?(e.secondsOnPage||0):0),0)})}}}const cs=[...new Set(records.map(r=>r.commission).filter(Boolean))].sort();$('commission').innerHTML='<option value="">Todas</option>'+cs.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('status').textContent='Datos actualizados.';draw()}catch(e){$('status').textContent='Error: '+e.message;console.error(e)}}
function filtered(){const c=$('commission').value,s=$('search').value.toLowerCase();return records.filter(r=>(!c||r.commission===c)&&(!s||`${r.name} ${r.email}`.toLowerCase().includes(s)))}
function rate(n,d){return d?Math.round(100*n/d)+'%':'—'}
function draw(){
 const a=filtered(),c=$('commission').value,s=$('search').value.toLowerCase();
 const eligible=attemptsData.filter(x=>(!c||x.commission===c)&&(!s||`${x.name} ${x.email}`.toLowerCase().includes(s)));
 const latest=new Map();for(const t of eligible){const old=latest.get(t.uid);if(!old||t.startedMs>old.startedMs||(t.startedMs===old.startedMs&&t.id>old.id))latest.set(t.uid,t)}
 const selected=$('attemptMode').value==='all'?eligible:[...latest.values()];
 const keys=new Set(selected.map(t=>t.uid+'|'+t.id));const selectedAnswers=a.filter(r=>{const t=eligible.find(t=>t.email===r.email&&t.id===r.attempt);return t&&keys.has(t.uid+'|'+t.id)});
 const correct=selectedAnswers.filter(r=>r.correct==='Correcta').length;
 $('summary').textContent=`${new Set(a.map(x=>x.email)).size} estudiantes · ${new Set(a.map(x=>x.email+'|'+x.attempt)).size} intentos · ${a.length} respuestas guardadas`;
 $('metrics').innerHTML=[['Estudiantes',new Set(selected.map(t=>t.uid)).size],['Intentos en vista',selected.length],['Aciertos automáticos',rate(correct,selected.length*questions.length)],['Respuestas pendientes',selectedAnswers.filter(r=>r.correct==='No automática').length]].map(([label,val])=>`<div class="metric"><strong>${esc(val)}</strong><span>${esc(label)}</span></div>`).join('');
 const sections=[...new Set(questions.map(q=>q.section||'Sin bloque'))];
 $('blockChart').innerHTML=sections.map(sec=>{const count=questions.filter(q=>(q.section||'Sin bloque')===sec).length,rows=selectedAnswers.filter(r=>r.section===sec),n=rows.filter(r=>r.correct==='Correcta').length,den=count*selected.length,pct=den?100*n/den:0;return `<div class="chartrow"><div class="chartlabel">${esc(sec)} <span>${n}/${den} · ${rate(n,den)}</span></div><div class="track"><div class="fill" style="width:${pct}%"></div></div></div>`}).join('')||'<p>Sin preguntas configuradas.</p>';
 const difficulty=questions.map((q,i)=>{const rows=selectedAnswers.filter(r=>r.question===i+1),bad=rows.filter(r=>r.correct==='Incorrecta').length,ok=rows.filter(r=>r.correct==='Correcta').length;return {i,q,bad,ok,missing:selected.length-rows.length,den:bad+ok}}).filter(x=>x.den>0).sort((x,y)=>(y.bad/y.den)-(x.bad/x.den)||y.bad-x.bad).slice(0,8);
 $('hardQuestions').innerHTML=difficulty.length?difficulty.map(x=>`<div class="difficulty"><strong>Pregunta ${x.i+1} · ${rate(x.bad,x.den)} de errores</strong><div>${esc(x.q.prompt)}</div><small>${x.bad} incorrectas / ${x.den} corregidas · ${Math.max(0,x.missing)} sin responder</small></div>`).join(''):'<p class="muted">Todavía no hay respuestas corregidas para analizar.</p>';
 $('attemptRows').innerHTML=selected.sort((x,y)=>y.startedMs-x.startedMs).map(t=>{const rows=selectedAnswers.filter(r=>r.email===t.email&&r.attempt===t.id),ok=rows.filter(r=>r.correct==='Correcta').length,bad=rows.filter(r=>r.correct==='Incorrecta').length,pending=rows.filter(r=>r.correct==='No automática').length;return `<tr>${[t.name,t.commission,t.started,t.id,`${rows.length}/${questions.length}`,ok,bad,pending,rate(ok,questions.length)].map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`}).join('')||'<tr><td colspan="9">Sin intentos para estos filtros.</td></tr>';
 $('rows').innerHTML=a.map(r=>`<tr>${[r.name,r.email,r.commission,r.attempt,r.started,r.question,r.prompt,r.response,r.correct,r.revisions,r.views,r.seconds].map((x,i)=>`<td ${i===6||i===7?'class="long"':''}>${esc(x)}</td>`).join('')}</tr>`).join('');
}
$('export').onclick=()=>{const cols=['name','email','commission','attempt','started','question','prompt','response','correct','revisions','views','seconds'],rows=[cols,...filtered().map(r=>cols.map(c=>String(r[c]??'')))];const csv='\ufeff'+rows.map(row=>row.map(s=>'"'+s.replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));let a=document.createElement('a');a.href=url;a.download='contabilidad_gerencial_respuestas.csv';a.click();URL.revokeObjectURL(url)};
